name-template: 'VSCode Extension v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION-vscode-extension'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed

  This release contains updates to the CDDL VS Code Language Server Extension.

  $CHANGES

  ## Full Changelog

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION-vscode-extension

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📖 Documentation'
    labels:
      - 'documentation'
exclude-labels:
  - 'skip-changelog'
