stages:
  - template: azure/stages.yml@templates
    parameters:
      minrust: 1.36.0
      codecov_token: $(CODECOV_TOKEN_SECRET)
            
resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: anweiss

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'