; Basic CDDL test file for completion testing
person = {
	name: tstr,
	age: uint,
	email: tstr
	"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
}

address = { street: tstr, city: tstr, zipcode: tstr }

; Test completion at beginning of file
