[package]
name = "cddl-codegen"
description = "Rust source code generation from CDDL definitions"
repository = "https://github.com/anweiss/cddl"
license = "MIT"
version = "0.1.0"
authors = ["Andrew Weiss <andrew.weiss@outlook.com>"]
edition = "2021"
rust-version = "1.88.0"
readme = "README.md"

[dependencies]
cddl = { version = "0.10.7", path = ".." }
