name: Draft release for VSCode Extension
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release-vscode-extension.yml'
      - 'cddl-lsp/**'

jobs:
  draft-release:
    name: Draft Release for VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: vscode-extension-release-drafter.yml
          publish: ${{ startsWith(github.ref, 'refs/tags') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
